name: Badminton Court Availability Checker

on:
  schedule:
    # Run every 30 minutes
    #- cron: "*/30 * * * *"
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  check-availability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser libxss1 libnss3 libatk-bridge2.0-0 libgtk-3-0 libgbm1

      - name: Create .env file
        run: |
          echo "EMAIL=${{ secrets.EMAIL }}" > .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }}" >> .env

      - name: Run availability checker
        run: node index.js
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
