name: Badminton Court Availability Checker

on:
  schedule:
    # Run every 30 minutes but not between 11 PM and 6:30 AM AEST
    # AEST is UTC+10, so this is 1 PM - 8:30 PM UTC
    - cron: "*/30 8-12 * * *" # 6:30 PM - 11:00 PM AEST (8:30 AM - 1:00 PM UTC)
    - cron: "*/30 0-7 * * *" # 10:00 AM - 6:00 PM AEST (0:00 AM - 8:00 AM UTC)
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  check-availability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser libxss1 libnss3 libatk-bridge2.0-0 libgtk-3-0 libgbm1

      - name: Create .env file
        run: |
          echo "EMAIL=${{ secrets.EMAIL }}" > .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }}" >> .env

      - name: Run availability checker
        run: node index.js
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
